### ISSUE TITLE
I can't turn off the Context Menu

### ISSUE THREAD

**Issue by iroy2000** [jpribyl/react-hook-mathjax#2]
@jpribyl Thanks for this lib.

I'm trying to feed in

```
const mathJaxOptions = {
  enableExplorer: false,
  enableMenu: false,
};

<MathJaxProvider options={mathJaxOptions}>
  ...
</MathJaxProvider>
```

But I'm still able to see the Context Menu shows up.

This is based on the doc > http://docs.mathjax.org/en/latest/options/accessibility.html#explorer-extension-options

![Screen Shot 2020-12-07 at 1 56 52 PM](https://user-images.githubusercontent.com/487520/101410456-362a7700-3894-11eb-94ef-35cfccf4d179.png)

**Comment by jpribyl** [comment]
Hey @iroy2000 thanks for the issue! I won't have time to look fully into this for about a week - however take a look at my comment on this issue:
https://github.com/jpribyl/react-hook-mathjax/issues/1#issuecomment-739245787

I didn't realize that the provider was bubbling up and I wrapped `Tex2SVG` in its own provider. My guess is that the most recent comment I left on that issue may fix this one as well.

Please try that out and let me know if it works for you! If so, I can update the docs :muscle:

**Comment by iroy2000** [comment]
I just tried the comment above, it is still showing the menu.

**Comment by jpribyl** [comment]
@iroy2000 thanks for the update, I will probably have some time to look this weekend

**Comment by jpribyl** [comment]
@iroy2000 It appears that you have your options incorrect :smile:  try it like this:
```typescript
const mathJaxOptions = {
  options: {
    enableMenu: false,
  },
};
```

For future reference, this is also possible using css by wrapping the element in a tag containing `pointer-events: none`

**Comment by jpribyl** [comment]
If this works for you, then I think we can close this one!

**Comment by iroy2000** [comment]
Thanks, it works for me. Let me close this one.

**Comment by dimuska139** [comment]
It doesn't work for me, but `pointer-events: none` in CSS - is a reliable solution.

**Comment by ssmirnow** [comment]
Same here - after setting 

```
const mathJaxOptions = {
    options: { showMathMenu: false },
  };
```

 I get `MathJax(?): Invalid option "showMathMenu" (no default value).` and the package is not loading at all. Unfortunately `pointer-events: none` won't work in my case as I need the generated output to be clickable. 
  Any help would be appreciated @jpribyl

**Comment by jpribyl** [comment]
@ssmirnow you are getting that error because that is not a valid option. Please refer to this page for valid options http://docs.mathjax.org/en/latest/options/accessibility.html#explorer-extension-options

This package uses v3 of mathjax - so some old options may no longer be supported.

**Comment by ssmirnow** [comment]
Uhm, trying to use 
```
const mathJaxOptions = {
    options: { enableExplorer: false },
  };
  ```
also throws the same error ;)

**Comment by jpribyl** [comment]
From what I can see, you are now attempting to use an option from the Explorer Extension without actually loading that extension. It makes sense to me that you would get that error in this scenario - it is coming directly from MathJax and letting you know that you don't have that extension loaded. 

Please refer to section 8.4 here if you require that extension https://readthedocs.org/projects/mathjax/downloads/pdf/latest/. It is possible that it would require additional work to load it, I have not tried.

What exactly is your goal? Are you attempting to get the right click menu to turn off?

**Comment by jjjluisjjj** [comment]
> @iroy2000 It appears that you have your options incorrect 😄 try it like this:
> 
> ```ts
> const mathJaxOptions = {
>   options: {
>     enableMenu: false,
>   },
> };
> ```
> 
> For future reference, this is also possible using css by wrapping the element in a tag containing `pointer-events: none`

and where in WordPress do I have to put that code?
