### ISSUE TITLE
develop and build version behave differently

### ISSUE THREAD

**Issue by iroy2000** [jpribyl/react-hook-mathjax#3]
When I include it into our dependencies, it works fine in develop environment, it is including the following subsequent request.

![Screen Shot 2020-12-22 at 3 51 42 PM](https://user-images.githubusercontent.com/487520/102943726-b690d080-446d-11eb-975b-3da5664886ac.png)

But when I build the project and test it, I only can see this

![Screen Shot 2020-12-22 at 3 51 55 PM](https://user-images.githubusercontent.com/487520/102943754-cf00eb00-446d-11eb-96b2-489d6e3288ea.png)

**Comment by jpribyl** [comment]
@iroy2000 I'm not fully understanding what's wrong here - is it causing some error? Off the cuff, it may have to do with having some dev dependencies vs trying to ensure the bundle size is small for production.

**Comment by iroy2000** [comment]
@jpribyl  thanks for the response

It doesn't cause any error, but it caused functionality difference.  For example, the accessibility functionality is removed after the production build.

**Comment by jpribyl** [comment]
That is interesting :thinking:  accessibility seems quite important. I tried to pare down the package size for build but I am thinking now that maybe this should be included by default? You can certainly build the package yourself and include anything you want in it, but I'm guessing most people use MathJax for its accessibility.

@iroy2000 are there any other functionality differences that you have observed?

**Comment by iroy2000** [comment]
I finally have time get back to it, I'm still trying to figure out why the build version is missing files. 

In non-prod, it has this loader ( semantic-enrich ), but in prod build, it is missing this loader.  

![Screen Shot 2021-01-25 at 2 28 24 PM](https://user-images.githubusercontent.com/487520/105774028-a14e0c80-5f19-11eb-8a3a-1a7767993943.png)
